name: Déploiement sur serveur personnel

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer les sources
        uses: actions/checkout@v3

      - name: Copier les fichiers sur le serveur
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          source: "."
          target: "/home/deployer/flask-app"

      - name: Relancer le service Flask
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          script: |
            cd /home/deployer/flask-app
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flask-app
